### ISSUE TITLE
CSV-generated table missing first line

### ISSUE THREAD

**Issue by BrianStucky-USDA** [USDA-SCINet/scinet-site#461]
I noticed that on https://scinet.usda.gov/opportunities/scinet-aicoe-fellowships, the first line of the CSV file used to generate the table does not get included in the displayed table. I did not attempt to investigate why!

**Comment by MoeRichert-USDA** [comment]
Removed the line of code causing the issue. [462](https://github.com/USDA-SCINet/scinet-site/pull/462)
